### ISSUE TITLE
Incompatible with Icinga Web 2.11

### ISSUE THREAD

**Issue by MegaphoneJon** [Icinga/icingaweb2-module-generictts#10]
## Expected Behavior
module works as in <= 2.10.

## Current Behavior
"Class Not Found" errors.

E.g.:
```
Uncaught Error: Class 'Icinga\Web\Hook\TicketHook' not found in /usr/share/icingaweb2/modules/generictts/library/Generictts/Ticket.php:12
Stack trace:
#0 /usr/share/php/Icinga/Application/ClassLoader.php(303): require()
#1 [internal function]: Icinga\Application\ClassLoader->loadClass('Icinga\\Module\\G...')
#2 [internal function]: spl_autoload_call('Icinga\\Module\\G...')
#3 /usr/share/php/Icinga/Application/Hook.php(126): class_exists('Icinga\\Module\\G...')
#4 /usr/share/php/Icinga/Application/Hook.php(303): Icinga\Application\Hook::createInstance('Ticket', '\\Icinga\\Module\\...')
#5 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(55): Icinga\Application\Hook::first('Ticket')
#6 /usr/share/php/Icinga/Web/Controller/ActionController.php(169): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->prepareInit()
#7 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\
```

## Possible Solution
`/usr/share/icingaweb2/doc/80-Upgrading.md` has a section **Framework changes affecting third-party code** which reads, in part:

 * `Icinga\Web\Hook\TicketHook`: Use `Icinga\Application\Hook\TicketHook` instead.

I'm going to try to work on a PR, but time may not permit me to finish.

**Comment by stultitiophobia** [comment]
+1

**Comment by sylvainfaivre** [comment]
linking your PR https://github.com/Icinga/icingaweb2-module-generictts/pull/11
